
export const GET_SLIDER_PHOTOS = 'GET_SLIDER_PHOTOS';
export type GET_SLIDER_PHOTOS = typeof GET_SLIDER_PHOTOS;

export const RECEIVED_SLIDER_PHOTOS = 'RECEIVED_SLIDER_PHOTOS';
export type RECEIVED_SLIDER_PHOTOS = typeof RECEIVED_SLIDER_PHOTOS;

export const GET_CHATEAU_POSTS = 'GET_CHATEAU_POSTS';
export type GET_CHATEAU_POSTS = typeof GET_CHATEAU_POSTS;

export const RECEIVED_CHATEAU_POSTS = 'RECEIVED_CHATEAU_POSTS';
export type RECEIVED_CHATEAU_POSTS = typeof RECEIVED_CHATEAU_POSTS;

export const RECEIVED_FOOTER_SITEMAP_ITEMS = 'RECEIVED_FOOTER_SITEMAP_ITEMS';
export type RECEIVED_FOOTER_SITEMAP_ITEMS = typeof RECEIVED_FOOTER_SITEMAP_ITEMS;
