
export const GET_SLIDER_PHOTOS = 'GET_SLIDER_PHOTOS';
export type GET_SLIDER_PHOTOS = typeof GET_SLIDER_PHOTOS;

export const RECEIVED_SLIDER_PHOTOS = 'RECEIVED_SLIDER_PHOTOS';
export type RECEIVED_SLIDER_PHOTOS = typeof RECEIVED_SLIDER_PHOTOS;

export const GET_VILLA_DATA = 'GET_VILLA_DATA';
export type GET_VILLA_DATA = typeof GET_VILLA_DATA;

export const RECEIVED_VILLA_CONTENT = 'RECEIVED_VILLA_CONTENT';
export type RECEIVED_VILLA_CONTENT = typeof RECEIVED_VILLA_CONTENT;

export const GET_CHATEAU_POSTS = 'GET_CHATEAU_POSTS';
export type GET_CHATEAU_POSTS = typeof GET_CHATEAU_POSTS;

export const RECEIVED_CHATEAU_POSTS = 'RECEIVED_CHATEAU_POSTS';
export type RECEIVED_CHATEAU_POSTS = typeof RECEIVED_CHATEAU_POSTS;

export const GET_WEBSITE_CONTENT = 'GET_WEBSITE_CONTENT';
export type GET_WEBSITE_CONTENT = typeof GET_WEBSITE_CONTENT;

export const RECEIVED_WEBSITE_ENTRIES = 'RECEIVED_WEBSITE_ENTRIES';
export type RECEIVED_WEBSITE_ENTRIES = typeof RECEIVED_WEBSITE_ENTRIES;

export const RECEIVED_FOOTER_SITEMAP = 'RECEIVED_FOOTER_SITEMAP';
export type RECEIVED_FOOTER_SITEMAP = typeof RECEIVED_FOOTER_SITEMAP;

export const GET_FOOTER_SITEMAP = 'GET_FOOTER_SITEMAP';
export type GET_FOOTER_SITEMAP = typeof GET_FOOTER_SITEMAP;

export const CLOSE_INTRO_MESSAGE = 'CLOSE_INTRO_MESSAGE';
export type CLOSE_INTRO_MESSAGE = typeof CLOSE_INTRO_MESSAGE;

export const SELECTED_VACATION = 'SELECTED_VACATION';
export type SELECTED_VACATION = typeof SELECTED_VACATION;
